name: Check Markdown Links

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
    steps:
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: .github/workflows/markdown_check_config.json
        file-path: './README.md'
    